baseURL = 'https://cortlandmahoney.com/'
languageCode = 'en-us'
title = 'Cortland Mahoney'
theme = 'hugo-kiera'
sectionPagesMenu = 'main'
resourceDir = "../resources"
description = "A site about software projects and Cortland Mahoney"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[author]
    name = "Cortland Mahoney"           #Author name
    github = "ckmahoney"         #Github username
    